-- TABELAS
CREATE TABLE Cliente ( 
    codcliente   INT GENERATED by default as identity (start with 10000 increment by 1) NOT NULL,
    cpf        char(11) NOT NULL,
    cliente      varchar(50) NOT NULL,
    contato    char(11) NOT NULL
);
CREATE TABLE ClientexAnimal (
codclienteanimal INT GENERATED by default as identity (start with 10000 increment by 1) NOT NULL,
codcliente int NOT NULL,
codanimal int NOT NULL
);
CREATE TABLE Animal (
    codanimal     INT GENERATED by default as identity (start with 10000 increment by 1) NOT NULL,
    codraca      int NOT NULL,
    nomeanimal   varchar(50) NOT NULL,
    dtnascimento date NOT NULL
);
CREATE TABLE Atendimento (
    codatendimento INT GENERATED by default as identity (start with 10000 increment by 1) NOT NULL,
    codvet         int NOT NULL,
    codanimal      int NOT NULL,
    data1           date NOT NULL,
    hora           time NOT NULL,
    custototal       numeric(10,2) NOT NULL,
    pago           boolean    NOT NULL,
    retorno           boolean  NOT NULL,
    relatorio       Text NOT NULL
);
CREATE TABLE Veterinario (
    codvet            INT GENERATED by default as identity (start with 1000 increment by 1) NOT NULL,
    codespecializacao int NOT NULL,
    veterinario          varchar(50) NOT NULL,
    custobase          numeric(10,2) NOT NULL
);
 
CREATE TABLE Especializacao (
    codespecializacao INT generated by default as identity (start with 10 increment by 1) NOT NULL,
    especializacao      varchar(50) NOT NULL
);
 
CREATE TABLE Raca (
    codraca INT generated by default as identity (start with 1 increment by 1) NOT NULL,
	codespecie int NOT NULL,
    raca    varchar(50) NOT NULL
);
 
CREATE TABLE Especie (
    codespecie INT generated by default as identity (start with 1 increment by 1) NOT NULL,
    especie    varchar(50) NOT NULL
);
 
--Criar PKs
ALTER TABLE cliente ADD CONSTRAINT cliente_codcliente_PK PRIMARY KEY (codcliente);
 
ALTER TABLE animal ADD CONSTRAINT animal_codanimal_PK PRIMARY KEY (codanimal);
 
ALTER TABLE atendimento ADD CONSTRAINT atendimento_codatendimento_PK PRIMARY KEY (codatendimento);
 
ALTER TABLE veterinario ADD CONSTRAINT veterianario_codveterinario_PK PRIMARY KEY (codvet);
 
ALTER TABLE especializacao ADD CONSTRAINT especializacao_codespecializacao_PK PRIMARY KEY (codespecializacao);
 
ALTER TABLE raca ADD CONSTRAINT raca_codraca_PK PRIMARY KEY (codraca);
 
ALTER TABLE especie ADD CONSTRAINT especie_codespecie_PK PRIMARY KEY (codespecie);
 
ALTER TABLE clientexanimal ADD CONSTRAINT clientexanimal_codclienteanimal_PK PRIMARY KEY (codclienteanimal);
 
--Criar Fks
ALTER TABLE clientexanimal ADD CONSTRAINT clientexanimal_codcliente_FK FOREIGN KEY (codcliente) REFERENCES cliente (codcliente);
 
ALTER TABLE clientexanimal ADD CONSTRAINT clientexanimal_codanimal_FK FOREIGN KEY (codanimal) REFERENCES animal (codanimal);
 
ALTER TABLE animal ADD CONSTRAINT animal_codraca_FK FOREIGN KEY (codraca) REFERENCES raca (codraca);
 
ALTER TABLE raca ADD CONSTRAINT raca_codespecie_FK FOREIGN KEY (codespecie) REFERENCES especie (codespecie);
 
ALTER TABLE atendimento ADD CONSTRAINT atendimento_codvet_FK FOREIGN KEY (codvet) REFERENCES veterinario (codvet);
 
ALTER TABLE atendimento ADD CONSTRAINT atendimento_codanimal_FK FOREIGN KEY (codanimal) REFERENCES animal (codanimal);
 
ALTER TABLE veterinario ADD CONSTRAINT veterinario_codespecializacao_FK FOREIGN KEY (codespecializacao) REFERENCES especializacao (codespecializacao);
 
--CRIA AS UNIQUEs
ALTER TABLE cliente ADD CONSTRAINT cliente_cpf_uq UNIQUE (cpf);
 
--CRIA O CHECK
ALTER TABLE atendimento ADD CONSTRAINT atendimento_pago_ck CHECK (pago = True);
 
--CRIA O DEFAULT
ALTER TABLE veterinario ALTER COLUMN custobase SET DEFAULT 120.00;

